/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DAO.NhanVienDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class form_DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form form_DangNhap
     */
    public form_DangNhap() {
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btn_dangnhap);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_tendangnhap = new javax.swing.JTextField();
        txt_matkhau = new javax.swing.JPasswordField();
        btn_dangnhap = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_quenmatkhau = new javax.swing.JLabel();
        checkbox1 = new java.awt.Checkbox();
        AnhNen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng Nhập");
        setLocation(new java.awt.Point(400, 100));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Tên đăng nhập:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("Mật khẩu:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));
        getContentPane().add(txt_tendangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 240, 30));
        getContentPane().add(txt_matkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 240, 30));

        btn_dangnhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_dangnhap.setText("ĐĂNG NHẬP");
        btn_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhapActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 130, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 51));
        jLabel3.setText("CHÀO MỪNG ĐẾN TRANG ĐĂNG NHẬP");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 470, 70));

        txt_quenmatkhau.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_quenmatkhau.setForeground(new java.awt.Color(255, 0, 255));
        txt_quenmatkhau.setText("Quên mật khẩu");
        txt_quenmatkhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_quenmatkhauMouseClicked(evt);
            }
        });
        getContentPane().add(txt_quenmatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        checkbox1.setBackground(new java.awt.Color(153, 0, 153));
        checkbox1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        checkbox1.setForeground(new java.awt.Color(255, 255, 51));
        checkbox1.setLabel("Lưu mật khẩu ?");
        getContentPane().add(checkbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 110, 30));

        AnhNen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AnhNen.setForeground(new java.awt.Color(0, 204, 255));
        AnhNen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/hinh-nen-may-tinh-chat.jpg2_-scaled.jpg"))); // NOI18N
        getContentPane().add(AnhNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -7, 720, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhapActionPerformed
        String tenDN = txt_tendangnhap.getText();
        char[] matKhau = txt_matkhau.getPassword();
        if (tenDN.isEmpty() || matKhau.length == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
            if (tenDN.isEmpty()) {
                txt_tendangnhap.requestFocusInWindow();
            }
            if (matKhau.length == 0) {
                txt_matkhau.requestFocusInWindow();
            }
        } else {
            NhanVienDAO nhanVienDAO = new NhanVienDAO();
            String chucVu = nhanVienDAO.kiemTraDangNhap(tenDN, String.valueOf(matKhau));
            int ID_NV = nhanVienDAO.layIDNhanVien(tenDN, String.valueOf(matKhau));
            if(chucVu == null){
               JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu không đúng", "Lỗi", JOptionPane.ERROR_MESSAGE);
                txt_tendangnhap.requestFocusInWindow();
                txt_tendangnhap.selectAll();
            }else{
                if (chucVu.equals("Nhân viên bán hàng")) {
                     JOptionPane.showMessageDialog(this, "Đăng nhập thành công", "Đăng nhập", JOptionPane.INFORMATION_MESSAGE);
                    // Mở form trang chủ cho nhân viên
                     this.dispose();
                      trangchu trangChuNhanVienForm = new trangchu();
                      trangChuNhanVienForm.setVisible(true);
                      this.dispose();
                } else if (chucVu.equals("Quản lý")) {
                     JOptionPane.showMessageDialog(this, "Đăng nhập thành công", "Đăng nhập", JOptionPane.INFORMATION_MESSAGE);
                    // Mở form quản lý cho quản lý
                   Admin quanLyForm = new Admin();
                   quanLyForm.setVisible(true);
                   this.dispose();
                }
            }
        }
    }//GEN-LAST:event_btn_dangnhapActionPerformed

    private void txt_quenmatkhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_quenmatkhauMouseClicked
        JOptionPane.showMessageDialog(this, "Vui lòng liên hệ quản trị viên", "EEyy!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_txt_quenmatkhauMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Bạn có chắc muốn đóng cửa sổ này?", "Xác nhận đóng cửa sổ", 
        JOptionPane.YES_NO_OPTION);

        if (confirmed != JOptionPane.YES_OPTION) {
            // Nếu người dùng không chọn YES, không thực hiện hành động đóng form
            setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        } else {
            // Nếu người dùng chọn YES, thực hiện hành động đóng form
            dispose(); // Đóng cửa sổ
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnhNen;
    private javax.swing.JButton btn_dangnhap;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txt_matkhau;
    private javax.swing.JLabel txt_quenmatkhau;
    private javax.swing.JTextField txt_tendangnhap;
    // End of variables declaration//GEN-END:variables
}
